import { StreamTarget } from 'mp4-muxer'

import {
  cancelBrowserExportStream,
  finalizeBrowserExportStream,
  heartbeatBrowserExportStream,
  startBrowserExportStream,
  writeBrowserExportChunk,
  type BrowserExportStreamSession,
} from '@engine/backend'
import type { ExportSpec } from './spec'

export const DIRECT_OUTPUT_CHUNK_BYTES = 16 * 1024 * 1024
export const DIRECT_OUTPUT_MAX_PENDING_BYTES = 64 * 1024 * 1024

export interface BrowserDirectOutput {
  outputDir: string
  outputName: string
  estimatedBytes: number
  /** Stable stream id, generated by the UI so it can hard-cancel a dead worker. */
  requestId?: string
  /** Hybrid mode: Browser writes video-only; backend mixes audio + stream-copies video. */
  hybridSpec?: ExportSpec
}

export interface BrowserStreamTransport {
  start(req: BrowserDirectOutput): Promise<BrowserExportStreamSession>
  write(streamId: string, position: number, data: Uint8Array, signal?: AbortSignal): Promise<void>
  finalize(
    streamId: string,
    expectedSize: number,
    signal?: AbortSignal,
    onProgress?: (pct: number) => void,
    videoCodec?: 'h264' | 'hevc' | 'av1',
  ): Promise<string>
  cancel(streamId: string): Promise<void>
}

const backendTransport: BrowserStreamTransport = {
  start: (req) => startBrowserExportStream(
    req.outputDir,
    req.outputName,
    req.estimatedBytes,
    req.requestId,
    req.hybridSpec,
  ),
  write: writeBrowserExportChunk,
  finalize: finalizeBrowserExportStream,
  cancel: cancelBrowserExportStream,
}

/** Async random-access backend writer behind mp4-muxer's synchronous callback. */
export class BackendMp4StreamSink {
  readonly target: StreamTarget
  readonly reservedPath: string
  private readonly streamId: string
  private readonly transport: BrowserStreamTransport
  private tail: Promise<void> = Promise.resolve()
  private pendingBytes = 0
  private maxEnd = 0
  private failure: unknown = null
  private aborted = false
  private finalized = false
  private abortPromise: Promise<void> | null = null
  private readonly transportAbort = new AbortController()
  private heartbeatTimer: ReturnType<typeof setInterval> | null = null

  static async create(
    request: BrowserDirectOutput,
    transport: BrowserStreamTransport = backendTransport,
  ): Promise<BackendMp4StreamSink> {
    const session = await transport.start(request)
    return new BackendMp4StreamSink(session, transport)
  }

  constructor(session: BrowserExportStreamSession, transport: BrowserStreamTransport) {
    this.streamId = session.streamId
    this.reservedPath = session.path
    this.transport = transport
    // The muxer may need longer than the backend idle lease to produce its next
    // 16 MiB chunk on a very heavy timeline. Keep the lease alive independently
    // of media output cadence.
    if (transport === backendTransport) {
      this.heartbeatTimer = setInterval(() => {
        void heartbeatBrowserExportStream(this.streamId).catch(() => {})
      }, 30_000)
    }
    this.target = new StreamTarget({
      chunked: true,
      chunkSize: DIRECT_OUTPUT_CHUNK_BYTES,
      onData: (data, position) => this.acceptMuxerData(data, position),
    })
  }

  /** Public for the muxer callback and deterministic transport tests. */
  acceptMuxerData(data: Uint8Array, position: number): void {
    if (this.aborted || this.finalized || data.byteLength === 0) return
    // mp4-muxer owns/reuses its chunk buffers; the async transport needs a stable copy.
    const stable = data.slice()
    this.pendingBytes += stable.byteLength
    this.maxEnd = Math.max(this.maxEnd, position + stable.byteLength)
    const write = this.tail.then(async () => {
      if (this.aborted || this.failure) return
      await this.transport.write(this.streamId, position, stable, this.transportAbort.signal)
    })
    this.tail = write
      .catch((e) => {
        this.failure ??= e
      })
      .finally(() => {
        this.pendingBytes -= stable.byteLength
      })
  }

  private throwIfFailed(): void {
    if (this.failure) {
      throw this.failure instanceof Error
        ? this.failure
        : new Error(`Direct export stream failed: ${String(this.failure)}`)
    }
  }

  private stopHeartbeat(): void {
    if (this.heartbeatTimer !== null) clearInterval(this.heartbeatTimer)
    this.heartbeatTimer = null
  }

  /** Bound queued chunk copies even when encoding is much faster than disk/network. */
  private async waitWhile(
    shouldWait: () => boolean,
    isAborted?: () => boolean,
  ): Promise<void> {
    while (shouldWait()) {
      if (isAborted?.()) {
        await this.abort()
        throw new DOMException('Export cancelled', 'AbortError')
      }
      const checkpoint = this.tail
      await Promise.race([
        checkpoint,
        new Promise<void>((resolve) => setTimeout(resolve, 100)),
      ])
      this.throwIfFailed()
    }
  }

  async waitForCapacity(isAborted?: () => boolean): Promise<void> {
    this.throwIfFailed()
    if (this.pendingBytes < DIRECT_OUTPUT_MAX_PENDING_BYTES) return
    await this.waitWhile(
      () => this.pendingBytes >= DIRECT_OUTPUT_MAX_PENDING_BYTES / 2,
      isAborted,
    )
  }

  async finalize(
    isAborted?: () => boolean,
    signal?: AbortSignal,
    onProgress?: (pct: number) => void,
    videoCodec?: 'h264' | 'hevc' | 'av1',
  ): Promise<string> {
    const abortNow = () => { void this.abort() }
    signal?.addEventListener('abort', abortNow, { once: true })
    const abortMonitor = isAborted
      ? setInterval(() => {
          if (isAborted()) abortNow()
        }, 50)
      : null
    try {
      if (this.aborted) throw new DOMException('Export cancelled', 'AbortError')
      await this.waitWhile(() => this.pendingBytes > 0, isAborted)
      if (isAborted?.() || signal?.aborted) {
        await this.abort()
        throw new DOMException('Export cancelled', 'AbortError')
      }
      this.throwIfFailed()
      if (this.maxEnd <= 0) throw new Error('Direct export produced no MP4 bytes')
      const path = await this.transport.finalize(
        this.streamId,
        this.maxEnd,
        this.transportAbort.signal,
        onProgress,
        videoCodec,
      )
      if (this.aborted || signal?.aborted || isAborted?.()) {
        throw new DOMException('Export cancelled', 'AbortError')
      }
      this.finalized = true
      this.stopHeartbeat()
      return path
    } finally {
      if (abortMonitor !== null) clearInterval(abortMonitor)
      signal?.removeEventListener('abort', abortNow)
      if (this.aborted && this.abortPromise) await this.abortPromise
    }
  }

  async abort(): Promise<void> {
    if (this.finalized) return
    if (this.abortPromise) return this.abortPromise
    this.aborted = true
    this.transportAbort.abort()
    this.stopHeartbeat()
    this.abortPromise = this.transport.cancel(this.streamId).catch(() => {})
    await this.abortPromise
  }
}
